In [3]:
import numpy as np
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a = np.array([6, 5, 4, 7, 5, 2, 1, 2, 1, 3, 9, 7])
a.reshape(6,2)

array([[6, 5],
       [4, 7],
       [5, 2],
       [1, 2],
       [1, 3],
       [9, 7]])

In [6]:
b = np.array([[6, 5, 4, 7, 5, 2], \
              [1, 2, 1, 3, 9, 7]])
b * 2

array([[12, 10,  8, 14, 10,  4],
       [ 2,  4,  2,  6, 18, 14]])